// This file has been autogenerated from a class added in the UI designer.
namespace boites_dialogue
{
	public partial class EditorPrefsController : NSViewController
	{
		#region Application Access
		public static AppDelegate App {
			get { return (AppDelegate)NSApplication.SharedApplication.Delegate; }
		}
		#endregion

		#region Computed Properties
		[Export("Preferences")]
		public AppPreferences Preferences {
			get { return App.Preferences; }
		}
		#endregion

		#region Constructors
		public EditorPrefsController (IntPtr handle) : base (handle)
		{
		}
		#endregion
	}
}
