// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace boites_dialogue
{
	public partial class MainWindow : NSWindowController
	{
		public MainWindow()
		{
		}
	}
}
